/* Servidor local para Control de Económicos + Microsoft SQL Server. */
const http = require('http');
const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');
const { promisify } = require('util');
const execFileAsync = promisify(execFile);
const root = __dirname;
const envFile = path.join(root, '.env');
if (fs.existsSync(envFile)) for (const line of fs.readFileSync(envFile, 'utf8').split(/\r?\n/)) { const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, ''); }
const port = Number(process.env.PORT || 8080);
const sqlcmd = process.env.SQLCMD_PATH || 'sqlcmd';
const sql = { server: process.env.SQL_SERVER, database: process.env.SQL_DATABASE, user: process.env.SQL_USER, password: process.env.SQL_PASSWORD };

function configured() { return Boolean(sql.server && sql.database && (sql.user ? sql.password : true)); }
function sqlArgs(file) { const args = ['-S', sql.server, '-d', sql.database, '-b', '-I', '-C', '-f', '65001', '-w', '65535', '-y', '0', '-i', file]; if (sql.user) args.push('-U', sql.user, '-P', sql.password); else args.push('-E'); return args; }
async function runSql(statement) { if (!configured()) throw new Error('Falta configurar SQL_SERVER y SQL_DATABASE; para autenticación SQL también SQL_USER y SQL_PASSWORD.'); const file = path.join(root, `.sql-temp-${Date.now()}-${Math.random().toString(36).slice(2)}.sql`); await fs.promises.writeFile(file, statement, 'utf8'); try { const { stdout } = await execFileAsync(sqlcmd, sqlArgs(file), { windowsHide: true, maxBuffer: 50 * 1024 * 1024 }); return stdout; } finally { await fs.promises.unlink(file).catch(() => {}); } }
async function ensureTable() { await runSql(`IF OBJECT_ID('dbo.Economicos','U') IS NULL CREATE TABLE dbo.Economicos (id nvarchar(64) NOT NULL PRIMARY KEY, economico nvarchar(50) NOT NULL UNIQUE, marca nvarchar(150) NOT NULL, modelo nvarchar(150) NOT NULL, serie nvarchar(150) NOT NULL, categoria nvarchar(10) NOT NULL, folio nvarchar(50) NOT NULL, monto decimal(18,2) NULL, area nvarchar(150) NOT NULL, fecha date NOT NULL, estado nvarchar(30) NOT NULL, observaciones nvarchar(max) NULL, fotos nvarchar(max) NULL, actualizadoEn datetime2 NOT NULL DEFAULT sysdatetime());`); }
async function getRecords() { const output = await runSql(`SET NOCOUNT ON; SELECT id,economico,marca,modelo,serie,categoria,folio,CONVERT(varchar(30),monto) monto,area,CONVERT(char(10),fecha,23) fecha,estado,observaciones,fotos FROM dbo.Economicos ORDER BY economico FOR JSON PATH;`); const start = output.indexOf('['), end = output.lastIndexOf(']'); const json = start >= 0 ? output.slice(start, end + 1).replace(/\r?\n/g, '') : '[]'; return JSON.parse(json).map(r => ({ ...r, photos: r.fotos ? JSON.parse(r.fotos) : [] })); }
async function replaceRecords(records) { const clean = records.map(r => ({ ...r, photos: r.photos || [] })); const escaped = JSON.stringify(clean).replace(/'/g, "''"); await runSql(`SET XACT_ABORT ON; BEGIN TRANSACTION; DELETE FROM dbo.Economicos; DECLARE @json nvarchar(max)=N'${escaped}'; INSERT INTO dbo.Economicos (id,economico,marca,modelo,serie,categoria,folio,monto,area,fecha,estado,observaciones,fotos) SELECT id,economico,marca,modelo,serie,categoria,folio,TRY_CONVERT(decimal(18,2),monto),area,TRY_CONVERT(date,fecha),estado,observaciones,JSON_QUERY(fotos) FROM OPENJSON(@json) WITH (id nvarchar(64) '$.id', economico nvarchar(50) '$.economico', marca nvarchar(150) '$.marca', modelo nvarchar(150) '$.modelo', serie nvarchar(150) '$.serie', categoria nvarchar(10) '$.categoria', folio nvarchar(50) '$.folio', monto nvarchar(50) '$.monto', area nvarchar(150) '$.area', fecha nvarchar(20) '$.fecha', estado nvarchar(30) '$.estado', observaciones nvarchar(max) '$.observaciones', fotos nvarchar(max) AS JSON); COMMIT TRANSACTION;`); }
function reply(res, code, data, type = 'application/json') { res.writeHead(code, { 'Content-Type': `${type}; charset=utf-8`, 'Access-Control-Allow-Origin': '*' }); res.end(type === 'application/json' ? JSON.stringify(data) : data); }
function staticFile(req, res) { const name = req.url === '/' ? 'index.html' : decodeURIComponent(req.url.split('?')[0]).slice(1); const file = path.resolve(root, name); if (!file.startsWith(root) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return reply(res, 404, { error: 'No encontrado' }); const types = { '.html':'text/html', '.js':'application/javascript', '.css':'text/css', '.md':'text/markdown' }; reply(res, 200, fs.readFileSync(file), types[path.extname(file)] || 'application/octet-stream'); }
const server = http.createServer(async (req, res) => { try { if (req.method === 'OPTIONS') return reply(res, 204, ''); if (req.url === '/api/status') return reply(res, 200, { configured: configured() }); if (req.url === '/api/economicos' && req.method === 'GET') { await ensureTable(); return reply(res, 200, await getRecords()); } if (req.url === '/api/economicos' && req.method === 'PUT') { let body = ''; for await (const chunk of req) { body += chunk; if (body.length > 45 * 1024 * 1024) throw new Error('La carga supera el límite de 45 MB.'); } const records = JSON.parse(body); if (!Array.isArray(records)) throw new Error('Formato de datos inválido.'); await ensureTable(); await replaceRecords(records); return reply(res, 200, { ok: true, count: records.length }); } staticFile(req, res); } catch (error) { reply(res, 500, { error: error.message || 'Error del servidor' }); } });
server.listen(port, () => console.log(`Control de económicos disponible en http://localhost:${port}`));
